{% set version = "1.8.0" %}

package:
  name: logbook
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/L/Logbook/logbook-{{ version }}.tar.gz
  sha256: 487fa41539787bfa21a51fabd7f3ae8ae7f9e6679bb3e241d0f5f18a2fc37e9c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - cython
    - pip
  run:
    - python

test:
  imports:
    - logbook
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/getlogbook/logbook
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Logbook is a nice logging replacement

  description: |
    Logbook is a nice logging replacement.
  doc_url: http://logbook.readthedocs.org
  dev_url: https://github.com/getlogbook/logbook

extra:
  recipe-maintainers:
    - maresb
    - simonvh
    - Ryan-Dmello
