{% set version = "1.9.0" %}

package:
  name: logbook
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/L/Logbook/logbook-{{ version }}.tar.gz
  sha256: dc07e627111abcb5fb154996fcc83124d256715163f23cab3f4e8d8c334ccf2d

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - cython
    - pip
  run:
    - python

test:
  imports:
    - logbook
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/getlogbook/logbook
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Logbook is a nice logging replacement

  description: |
    Logbook is a nice logging replacement.
  doc_url: http://logbook.readthedocs.org
  dev_url: https://github.com/getlogbook/logbook

extra:
  recipe-maintainers:
    - maresb
    - simonvh
    - Ryan-Dmello
