{% set version = "1.7.0" %}

package:
  name: logbook
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/L/Logbook/Logbook-{{ version }}.tar.gz
  sha256: da4c22f8a5b0a0e9cf7b198f2ac935934b933a04b5a2d24ef3b1ffa2faeaa3c1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - pip
  run:
    - python

test:
  imports:
    - logbook

about:
  home: https://github.com/getlogbook/logbook
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Logbook is a nice logging replacement

  description: |
    Logbook is a nice logging replacement.
  doc_url: http://logbook.readthedocs.org
  dev_url: https://github.com/getlogbook/logbook

extra:
  recipe-maintainers:
    - maresb
    - simonvh
    - Ryan-Dmello
